[project]
name = "pocs"
version = "0.1.0"
description = "POC repo for various projects"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=1.2.10",
    "langchain-google-genai>=4.2.0",
    "langgraph>=1.0.8",
    "langgraph-cli[inmem]>=0.4.12",
]
